# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Antiqueruby' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Antiqueruby
    pod 'Google-Mobile-Ads-SDK'

  target 'Antiqueruby-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AntiquerubyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Antiqueruby-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Antiqueruby-tvOS


end
